version: "3.8"

services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: adam_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1qaz2wsx
      POSTGRES_DB: AdamMonitoring
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./iiot_init.sql:/docker-entrypoint-initdb.d/init.sql

  client:
    dns: [8.8.8.8, 8.8.4.4]
    build: { context: ., dockerfile: IIoT.Collector/Dockerfile, network: host }
    container_name: modbus_client
    environment:
      - ConnectionStrings__ADAMDB=Host=db;Port=5432;Database=AdamMonitoring;Username=admin;Password=1qaz2wsx
      - ModbusSettings__IpAddress=sim
      - ModbusSettings__Port=5020
      - Serilog__MinimumLevel=Debug
    depends_on: [db, sim]
    restart: always

  sim:
    build: { context: ./sim, network: host }
    container_name: modbus_sim
    ports: ["5020:5020"]
    restart: always

  gateway:
    dns: [8.8.8.8, 8.8.4.4]
    build: { context: ., dockerfile: IIoT.WebApi/Dockerfile, network: host }
    container_name: modbus_web_gateway
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__AdamMonitoring=Host=db;Port=5432;Database=AdamMonitoring;Username=admin;Password=1qaz2wsx
    ports: ["8080:80"]
    depends_on: [db]
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    network_mode: host
    restart: always
    command: ["tunnel", "run"]
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
      - TUNNEL_TRANSPORT_PROTOCOL=http2
      - TUNNEL_HEARTBEAT_INTERVAL=5s
      - TUNNEL_HEARTBEAT_COUNT=2
      - HTTP_PROXY=http://127.0.0.1:10809
      - HTTPS_PROXY=http://127.0.0.1:10809
      - NO_PROXY=localhost,127.0.0.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  pgdata:
